name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  greeting:
    if: github.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello peeps from the pipeline!'

  test-utils:
    if: github.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm run test-utils

  test-app:
    if: github.event == 'pull_request'
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55w0rd

      - name: Install dependencies
        run: npm install
      - name: Test app
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55w0rd npm run test-app

  test-app-live-db:
    if: github.event == 'pull_request'
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test app with live database
        run: NODE_ENV=production DATABASE_URL=${{ secrets.DATABASE_URL }} npm run test-app
  
  deploy-to-render:
    if: github.event == 'push'
    needs: test-app-live-db
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl ${{ secrets.DEPLOY_URL }}
