name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello peeps from the pipeline!'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm run test-utils

  test-app:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: ${{ secrets.DB_NAME }}
          postgresql user: ${{ secrets.DB_USER }}
          postgresql password: ${{ secrets.DB_PASSWORD }}

      - name: Install dependencies
        run: npm install

      - name: Test app
        run: PGDATABASE=${{ secrets.DB_NAME }} PGUSER=${{ secrets.DB_USER }} PGPASSWORD=${{ secrets.DB_PASSWORD }} npm run test-app
